project/TMS/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ticket.urls')),

]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()

project/ticket/urls.py
from django.contrib import admin
from django.urls import path
from ticket.views import *



urlpatterns = [

    path('', HomeView.as_view(),name='home'),
    # path('register', RegisterationView, name='register'),
    path('register', RegisterationView.as_view(), name='register'),
    path('login', CustomerLoginView.as_view(),name='login'),
    path('logout', LogoutView.as_view(),name='logout'),
    # path('logout', logoutuser,name='logout'),
    path('test', get_user_mobile,name='test'),
    path('newticket', CreateTicketView.as_view(),name='newticket'),
    # path('newticket', CreateTicketView,name='newticket'),
    path('ticketlist', ViewAllTicketView,name='ticketlist'),
    path('assigned_tickets', assigned_tickets,name='assigned_tickets'),
    path('update_ticket_status/<int:id>/', update_ticket_status,name='update_ticket_status'),
    path('report', ReportView.as_view(),name='report'),
    # path('report', report,name='report'),



]



#    {{form.user}} <br>    

#            <label for="">Mobile</label>
#             {{form.mobile}}<br><br>
#            <label for="">Assets</label>
#             {{form.assets}}<br><br>
#            <label for="">Priority</label>
#             {{form.priority}}<br><br>
#            <label for="">Serial No.</label>
#             {{form.serial_no}}<br><br>
#            <label for="">Model No</label>
#             {{form.model_no}}<br><br>
#            <label for="">Tcketstatus</label>
#             {{form.ticketstatus}} <br> <br>
#             <label for="">Assign To</label>
#             {{form.assigned_to}}

project/ticket/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from ticket.managers import Usermanager
from django.utils.timezone import now
from django.db.models import Q
from django.core.validators import MinLengthValidator

# Create your models here.
ROLE = (
        ('Agent', 'Agent'),
        ('Subadmin', 'Subadmin'),
        ('User', 'User'),
    )

PRIORITY = (
        ('Low', 'Low'),
        ('Medium', 'Medium'),
        ('High', 'High'),
        ('Emergency', 'Emergency'),
    )    

STATUS = (
        ('Pending', 'Pending'),
        ('Approved', 'Approved'),
        ('Ready-to-dispatch', 'Ready-to-dispatch'),
        ('Dispatched', 'Dispatched'),
        ('Closed', 'Closed'),

    )


class BaseModel(models.Model):
    created_at = models.DateField(auto_now_add= True)
    created_by = models.CharField(max_length=255, default='dj')
    updated_at = models.DateField(auto_now= True)
    updated_by = models.CharField(max_length=255, default='dj')


    class Meta:
        abstract = True


class CustomUserModel(BaseModel,AbstractUser):
    username = None
    email = models.EmailField(unique=True)
    # is_email_verified = models.BooleanField(default=False)
    mobile= models.CharField(max_length=10,validators=[MinLengthValidator(10)],null=False, blank=False)
    role = models.CharField(choices=ROLE,max_length =20,null=False,blank=False) 
    profile_pic = models.ImageField(upload_to='profile_pics',null=True, blank=True)
    status = models.BooleanField(default=True)
    object = Usermanager()


    def __str__(self):
        return self.email

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []


class Ticket(BaseModel):
    user = models.ForeignKey(CustomUserModel, on_delete=models.CASCADE, limit_choices_to=Q(role='User'))
    mobile= models.CharField(max_length=10,null=False, blank=False)
    assets = models.CharField(max_length =200,blank=False,null=False)
    priority = models.CharField(choices=PRIORITY, max_length =20,blank=False,null=False)
    serial_no = models.CharField(max_length =15,validators=[MinLengthValidator(5)],blank=False,null=False)
    model_no = models.CharField(max_length =15,validators=[MinLengthValidator(5)],blank=False,null=False)
    ticketstatus = models.CharField(choices=STATUS, max_length =20,blank=False,default='Pending')
    assigned_to = models.ForeignKey(CustomUserModel, on_delete=models.CASCADE, limit_choices_to=Q(role='Agent'),related_name='assigned_to')

    






     

project/ticket/forms.py
from django import forms
from .models import *


class SignupForm(forms.ModelForm):
    class Meta:
        model= CustomUserModel
        fields=('email','mobile', 'first_name', 'last_name', 'role', 'profile_pic','status')
        # fields = "__all__"


class DateInput(forms.DateInput):
    input_type = 'date'


class TicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ['user','mobile','assets','priority','serial_no','model_no','ticketstatus','assigned_to']





    # widgets = {
    #             'birthdate': SelectDateWidget(attrs = {
    #              },years = range(1920, 2017),),
    #          }

project/ticket/views.py
from django.shortcuts import render
from .forms import SignupForm, TicketForm
from .models import CustomUserModel,Ticket
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login,logout
from django.shortcuts import render,HttpResponseRedirect,redirect
from django.contrib import messages
from django.views import View
from django.views.generic import FormView, RedirectView,TemplateView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy,reverse
import datetime
from django.contrib.auth.hashers import make_password
import random
from django.db.models import Count
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.dateparse import parse_date
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required


class RegisterationView(FormView):
    template_name = 'signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('home')
   
    def form_valid(self,form):
        user = form.save(commit=False)
            # auto_pass = request.POST.get('first_name').capitalize()+'@'+str(random.randint(1111, 9999)) 
        if self.request.POST.get('role')=='Subadmin':
            user.is_staff = True

        if self.request.POST.get('role')=='Agent':
            user.is_active = True

        if self.request.POST.get('role')=='User':
            user.is_active = False
                
        auto_pass = 'User'+'@'+'1234'
        hash_pass = make_password(auto_pass)
        user.password = hash_pass
        user.save()
        
        return super(RegisterationView, self).form_valid(form)


class CustomerLoginView(View):
    
    def get(self,*args,**kwargs):
        form = AuthenticationForm()
        return render(self.request, 'login.html',{'form':form})

    def post(self,request,*args,**kwargs):
        fm = AuthenticationForm(request, data=request.POST)
        # umail = request.POST.get('username')
        # upass = request.POST.get('password')
        # user = authenticate(username=umail,password=upass)
        # print(user,'&&&&&&&&&&&&&&&&')
     
        if fm.is_valid():
            umail = fm.cleaned_data.get('username')
            upass = fm.cleaned_data.get('password')
            user = authenticate(username=umail,password=upass)

            if user is not None or user.is_active==True or user.is_superuser==True or user.is_staff==True:
                login(self.request, user)
                return redirect('home')

            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            
        return render(request, 'login.html',{'form':fm})
        

# def logoutuser(request):
#     logout(request)
#     return redirect('home')

class LogoutView(RedirectView):
    url = '/'
    def get(self, request):
        logout(request) 
        return super(LogoutView, self).get(request)


class HomeView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs) 
        today = datetime.date.today()
        context = {
        'active_ticket' : Ticket.objects.filter(created_at=today).count(),
        'closed_ticket' : Ticket.objects.filter(ticketstatus='Closed').count(),
        'resolved_ticket' : Ticket.objects.filter(updated_at=today,ticketstatus='Dispatched').count(),
        'agents_count' : Ticket.objects.values('assigned_to').annotate(Count('assigned_to')).count()
               }
        return context


def ViewAllTicketView(request):
    ticket = Ticket.objects.all()
    return render(request, 'ticket_report.html',{'ticket':ticket})
    

class CreateTicketView(LoginRequiredMixin,CreateView):
    form_class = TicketForm
    template_name = 'newticket.html'
    login_url = 'login'
    redirect_field_name = 'login'
    success_url = '/'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class ReportView(LoginRequiredMixin,ListView):
    model = Ticket
    template_name = 'report.html'
    login_url = 'login'
    redirect_field_name = 'login'
    context_object_name = 'tickets'
    paginate_by = 2

    
    def post(self,request):
        search_term = request.POST.get('search', None)
        froms = parse_date(request.POST.get('from-date'))
        to = parse_date(request.POST.get('to-date'))
        status = request.POST.get('status')
        priority = request.POST.get('priority')


        if search_term:
            tickets =Ticket.objects.filter(user__first_name__icontains=search_term)
        
        elif status:
            tickets =Ticket.objects.filter(ticketstatus__icontains=status)
            
        elif froms and to:
            tickets = Ticket.objects.filter(created_at__range=(froms, to))

        elif froms and to and status and priority:
            tickets = Ticket.objects.filter(created_at__range=(froms, to),ticketstatus=status,priority=priority)    
        
        else: 
            tickets = Ticket.objects.all()

        return render(request, 'report.html',{'tickets':tickets})
        

def get_user_mobile(request):
    id = request.GET['id']
    user = CustomUserModel.objects.get(id=id)
    data = {'mobile':user.mobile}
    return JsonResponse(data)
        

@login_required(login_url='login')
def assigned_tickets(request):
    tickets = Ticket.objects.filter(assigned_to =request.user)
    return render(request, 'assigned_tickets.html',{'tickets':tickets})


@login_required(login_url='login')
def update_ticket_status(request,id):
    ticket_obj = Ticket.objects.get(id=id)
    ticket_obj.ticketstatus = request.POST.get('status')
    ticket_obj.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))



# def CreateTicketView(request):
#     form = TicketForm()
    
#     if request.method == 'POST':
#         form = TicketForm(request.POST)
#         form.save()
#         # messages.success(request,'ticket created successfully')
#         return redirect('home')

#     return render(request, 'newticket.html',{'form':form})



# def RegisterationView(request):

#     form = SignupForm()
#     if request.method == 'POST':  
#         form = SignupForm(request.POST,request.FILES or None)
#         if form.is_valid():

#             user = form.save(commit=False)
#             # auto_pass = request.POST.get('first_name').capitalize()+'@'+str(random.randint(1111, 9999)) 
#             if request.POST.get('role')=='Subadmin':
#                 user.is_staff = True

#             if request.POST.get('role')=='Agent':
#                 user.is_active = True

#             if request.POST.get('role')=='User':
#                 user.is_active = False
                
#             # auto_pass = request.POST.get('first_name').capitalize()+'@'+'1234'
#             auto_pass = 'User'+'@'+'1234'
#             hash_pass = make_password(auto_pass)
#             user.password = hash_pass
#             user.save()

#             return redirect('home')

#     return render(request, 'signup.html',{'form':form})

project/ticket/templates/assigned_tickets.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Assigned Tickets {% endblock %}
{% block main %}


<body class="animsition">
    <div class="page-wrapper">
            <div id="maintiks" style="max-width:90%;margin:auto;">

            <div class="col-lg-9" style="flex: 0 0 100% !important;max-width: 100% !important;">
                                            <div class="table-responsive table--no-card m-b-30">
                                                <table class="table table-borderless table-striped table-earning">
                                                    <thead>
                                                        <tr>
                                                          <form method="POST">{% csrf_token %}
                                                            <th><button name="ordr" type="submit" style="color:white;" value="-id">Ticket ID</button></th>
                                                            <th><button name="ordr" type="submit" style="color:white;" value="-type">Email</button></th>
                                                            <th><button name="ordr" type="submit" style="color:white;" value="-date_created">Mobile </button></th>
                                                            <th>Date Created</th>
                                                            <th><button name="ordr" type="submit" style="color:white;" value="-status">Priority </button></th>
                                                            <th><button name="ordr" type="submit" style="color:white;" value="-title">Assets </button></th>
                                                            <th>Status</th>
                                                            <th>Update-status</th>
                                                          </form>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                      {% for ticket in tickets %}
                                                        <tr>
                                                            <td>{{ticket.id}}</td>
                                                            <td>{{ticket.user}}</td>
                                                            <td>{{ticket.mobile}}</td>
                                                            <td>{{ticket.created_at}}</td>
                                                            <td style=color:#FF0000>{{ticket.priority}}</td>
                                                            <td>{{ ticket.assets}}</td>
                                                            <td style=color:#FF0000>

                                                              <form action="{% url 'update_ticket_status' ticket.id %}" method="POST">
                                                                  {% csrf_token %}
                                                                
                                                                   <select name="status" id="cars">
                                                                     <option value="{{ticket.ticketstatus}}">{{ticket.ticketstatus}}</option>
                                                                     <option value="Approved">Approved</option>
                                                                     <option value="Ready-to-dispatch">Ready-to-dispatch</option>
                                                                     <option value="Dispatched">Dispatched</option>
                                                                     <option value="Closed">Closed</option>
                                                                   </select>
                                                                   <br><br>
                                                            </td>
                                                            

                                                            <td>
                                                              <button type="submit"  class="btn btn-primary mb-1">Update</button>
                                                            </td>
                                                        </form>

                                                        </tr>
                                                      {% endfor %}
                                                    </tbody>
                                                </table>
                                            </div>
                                           
                                        </div>

            </div>
            <!-- END MAIN-->
      {% endblock %}

project/ticket/templates/base.html
{% load static %}
{%load crispy_forms_tags %} 
<!doctype  html>
<html  lang="en">
<head>

{% block head %}
{% endblock %}

    <meta http-equiv="refresh" content="60">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="{% static 'home/css/font-face.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'home/vendor/font-awesome-4.7/css/font-awesome.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'home/vendor/font-awesome-5/css/fontawesome-all.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'home/vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet" media="all">

    <!-- Bootstrap CSS-->
    <link href="{% static 'home/vendor/bootstrap-4.1/bootstrap.min.css' %}" rel="stylesheet" media="all">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Vendor CSS-->
    <link href="{% static 'home/vendor/animsition/animsition.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'home/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'home/vendor/wow/animate.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'home/vendor/css-hamburgers/hamburgers.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'home/vendor/slick/slick.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'home/vendor/select2/select2.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'home/vendor/perfect-scrollbar/perfect-scrollbar.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'css/pop.css' %}" rel="stylesheet" media="all">
    <!-- Main CSS-->
    <link href="{% static 'home/css/theme.css' %}" rel="stylesheet" media="all">

{% block bootstrap %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
{% endblock %}

{% block scripts %}
{% endblock %}
</head>
<body class="text-center">
    <body class="animsition">
        <div class="page-wrapper">
            <!-- HEADER DESKTOP-->
            <header class="header-desktop3 d-none d-lg-block">
                <div class="section__content section__content--p35">
                    <div class="header3-wrap">
                        <div class="header__logo">
                            <a href="/">
                                <img src="{% static 'img/home.png' %}" alt="Company" />
                            </a>
                        </div>
                        <div class="header__navbar">
                            <ul class="list-unstyled">
                              <li>
                                  <a href="{% url 'home' %}">
                                      <i class="fas fa-home"></i>
                                      <span class="bot-line"></span>Home</a>
                              </li>
                              {% if user.is_staff and not user.is_superuser  %}
                                <li>
                                    <a href="{% url 'newticket' %}">
                                        <i class="fas fa-plus"></i>
                                        <span class="bot-line"></span>New Ticket</a>
                                </li>
                                {% endif %}
                               
                                {% if user.is_superuser %}
                                <li class="has-sub">
                                    <a href="#">
                                        <i class="fas fa-user-secret"></i>
                                        <span class="bot-line"></span>Admin Only</a>
                                    <ul class="header3-sub-list list-unstyled">
                                        <li>
                                            <a href="{% url 'register' %}">Add Subadmin/Agent</a>
                                        </li>
                                        
                                        <li>
                                            <a href="">Users List</a>
                                        </li>
                                    </ul>
                                </li>
    
                                {% elif user.is_staff %}
                                <li class="has-sub">
                                    <a href="#">
                                        <i class="fas fa-user-secret"></i>
                                        <span class="bot-line"></span>Sub-Admin Only</a>
                                    <ul class="header3-sub-list list-unstyled">
                                        <li>
                                            <a href="{% url 'register' %}">Add User</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'newticket' %}">Generate Ticket</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'report' %}">Tickets Report</a>
                                        </li>
                                       
                                    </ul>
                                </li>
                                {% elif user.is_active and not user.is_staff and not user.is_superuser  %}
                                <li class="has-sub">
                                    <a href="#">
                                        <i class="fas fa-user-secret"></i>
                                        <span class="bot-line"></span>Agent Only</a>
                                    <ul class="header3-sub-list list-unstyled">
                                        <li>
                                            <a href="{% url 'assigned_tickets' %}">Assigned Ticket</a>
                                        </li>
                                    </ul>
                                </li>
                                {% else %}
                                {% endif %}
                             
                            </ul>
                        </div>
                        <div class="header__tool">
                            
                            
                            <div class="account-wrap">
                                <div class="account-item account-item--style2 clearfix js-item-menu">
                                    <div class="image">
                                        <img src="{% static 'img/userlogo.jpg' %}" alt="{{ user.first_name }} {{ user.last_name }}" />
                                    </div>
                                    <div class="content">
                                        <a class="js-acc-btn" href="#">{{ user.first_name }} </a>
                                    </div>
                                    <div class="account-dropdown js-dropdown">
                                        <div class="info clearfix">
                                            <div class="image">
                                                <a href="#">
                                                    <img src="{% static 'img/userlogo.jpg' %}" alt="{{ user.first_name }} {{ user.last_name }}" />
                                                </a>
                                            </div>
                                            <div class="content">
                                                <h5 class="name">
                                                    <a href="">{{ user.first_name }}</a>
                                                </h5>
                                                <span class="email">{{ user.email }}</span>
                                            </div>
                                        </div>
                                       
                                        {% if user.is_superuser or user.is_staff %}
                                        <div class="account-dropdown__footer">
                                            <a href="{% url 'register' %}"><i class="zmdi zmdi-power"></i>Register Now</a>
                                        </div>
                                        {% endif %}
                                         
                                         
                                        {% if user.is_authenticated %}

                                        
                                        <div class="account-dropdown__footer">
                                            <a href="{% url 'logout' %}"><i class="zmdi zmdi-power"></i>Logout</a>
                                        </div>
                                        {% else %}

                                        
                                        <div class="account-dropdown__footer">
                                            <a href="{% url 'login' %}"><i class="zmdi zmdi-power"></i>Login :{{ user.last_login }}</a>
                                        </div>
    
                                        {% endif %}
    
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </header>

            
               
            {% block main %}

            {% endblock %}


    <section class="p-t-60 p-b-20">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="copyright">
                        <p>Copyright ©  Company. All rights reserved.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

      {% block footer %}
      {% endblock %}

      {% block script %}
      {% endblock %}

      <script src="{% static 'home/vendor/jquery-3.2.1.min.js' %}"></script>
      <!-- Bootstrap JS-->
      <script src="{% static 'home/vendor/bootstrap-4.1/popper.min.js' %}"></script>
      <script src="{% static 'home/vendor/bootstrap-4.1/bootstrap.min.js' %}"></script>
      <!-- Vendor JS       -->
      <script src="{% static 'home/vendor/slick/slick.min.js' %}">
      </script>
      <script src="{% static 'home/vendor/wow/wow.min.js' %}"></script>
      <script src="{% static 'home/vendor/animsition/animsition.min.js' %}"></script>
      <script src="{% static 'home/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js' %}">
      </script>
      <script src="{% static 'home/vendor/counter-up/jquery.waypoints.min.js' %}"></script>
      <script src="{% static 'home/vendor/counter-up/jquery.counterup.min.js' %}">
      </script>
      <script src="{% static 'home/vendor/circle-progress/circle-progress.min.js' %}"></script>
      <script src="{% static 'home/vendor/perfect-scrollbar/perfect-scrollbar.js' %}"></script>
      <script src="{% static 'home/vendor/chartjs/Chart.bundle.min.js' %}"></script>
      <script src="{% static 'home/vendor/select2/select2.min.js' %}"></script>
      <script src="{% static 'js/pop.js' %}"></script>
      <!-- Main JS-->
      <script src="{% static 'home/js/main.js' %}"></script>
      <!-- end document-->

 </body>
</html>

project/ticket/templates/login.html
{% extends 'base.html' %}
{% load static %}
{%load crispy_forms_tags %} 

{% block main %}

 <div class="page-content--bgf7" >
    <!-- MAIN-->
    <div class="main-content" style="padding:1% 10%;max-width:1000px;margin:auto;">
    <form method="post" class="form-signin" enctype='multipart/form-data' novalidate>
    <img src="{% static 'img/logo.png' %}" style="width:50%;margin-bottom: 32px;" class="logod" alt="company logo">
    <h1 class="h3 mb-3 font-weight-normal">Login</h1>
    {% csrf_token %}



<style>
  .errorlist
  {
      color: red;
  }
</style>

  {{forms.non_field_errors }}
  {% for fm in form %}
       <div>
        {{fm.label_tag}} {{fm}} <span class="errorlist">
        {{fm.errors|striptags}} </span>
       </div>  
    {% endfor %}

<br>
    <button type="submit" class="signbtn btn btn-primary" style="width:48%;">Login </button> <br> <br>
    <a href="{% url 'register' %}">Not an User? <b>Register</b></a>

    </form>
    </div>
    {% endblock %}

project/ticket/templates/newticket.html
{% extends 'base.html' %}
{% load static %}
{% block scripts %}

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

<script>

  $(document).ready(function(){
    $('select#id_user').change(function (event) {
           
               var optionSelected = $(this).find("option:selected");
               var valueSelected  = optionSelected.val();
          
               $.ajax({
            type:"GET",
            url:"{% url 'test'  %}",
            
            data: {id :valueSelected},
            success:function(data){
                document.getElementById("id_mobile").value =data.mobile
            }
            })
         }
        )
     }
    )

</script>

{% endblock %}



{% block main %}

<style>
  .errorlist
  {
      color: red;
  }
</style>
<body class="animsition">
    <div class="page-wrapper">
  
        <div class="page-content--bgf7" >
            <div class="main-content" style="padding:100px 200px;max-width:1000px;margin:auto;" >
            <form method="POST" class="form-signin" style="background-color: #d3d3d3;" novalidate> 
            <img src="{% static 'img/logo.png' %}" style="width:50%;margin-bottom: 32px;" class="logod" alt="company logo">
            <h1 class="h3 mb-3 font-weight-normal" style="color: white"> Generate Ticket</h1> <br>
            {% csrf_token %}
            
       
        {{forms.non_field_errors }}
        {% for fm in form %}
             <div>
              {{fm.label_tag}} {{fm}} <span class="errorlist">
              {{fm.errors|striptags}} </span>
             </div>  
          {% endfor %}

            <button type="submit" class="signbtn btn btn-primary" style="width:48%;">Submit Ticket </button> 
            </form>
            <br>
            </div>

	
{% endblock %}
      